### ISSUE TITLE
[BUG] Inconsistent Behavior of PatternVertex Ranking

### ISSUE THREAD

**Issue by MeloYang05** [longbinlai/GraphScope#139]
**Describe the bug**
Two pattern with the same structure but with different PatternIds may have different PatternVertex Ranking, which influence the results of Pattern Encoding

**To Reproduce**
test ranking case 17

**Environment (please complete the following information):**
 - GraphScope version: the latest version of branch ir_catalog
 - OS: macOS Monterey
 - Version 12.3.1

**Comment by tonyLyx1** [comment]
The PatternVertex Ranking has now changed to a naive implementation, and the latest version is on [ir_catalog_rank](https://github.com/longbinlai/GraphScope/blob/ir_catalog_rank/research/query_service/ir/core/src/catalogue/pattern.rs) branch. The basic idea is to iteratively do shallow comparison for ranks (similar to the initial rank comparison before) and then update the order of neighbor edges & vertices. This naive implementation is easy to understand and uses far few lines of codes. The only problem is that there are still many duplicated comparisons during the process, which is the next part for optimization.

Now, all the test cases should be OK. More test cases are always welcomed!

**Comment by tonyLyx1** [comment]
If you don't have any other questions regarding the inconsistent behavior of PatternVertex Ranking, I will close this issue. Please raise another issue for any new questions.
